### PR TITLE
Update to plugin-seed format

### PR DESCRIPTION
**Pull request by keerl**
This is the first plugin I have converted to the new community plugin-seed I made and would really like to try out.

- Cleaned up and standardized a lot of files (eslint, prettier, etc).
- Added/re-wrote all demos (Angular, React, Svelte, and Vue).
  - Only `demo-snippets` should be modified.
  - Actual demo directories are submodules that will be common across ALL community plugins.
  - All files in `demo-snippets` directory should load in IDE without any errors (as long as the demo app for that snippet is built).
- Re-wrote README
- Updated all dependencies (core, platforms, Angular, etc) 
- Fixed Svelte typings
- Updated React typings
- Standardized top-level `package.json` and scripts.

---

To test this branch:

You much checkout this branch and initialize the submodules:

```bash
git clone https://github.com/nativescript-community/ui-pager.git
cd ui-pager
git checkout feature/plugin-seed
git submodule update --init
```

### Install Dependencies:
```bash
npm i # or 'yarn install' or 'pnpm install'
```

### Interactive Menu (optional):
To start the interactive menu, run `npm start` (or `yarn start` or `pnpm start`). This will list all of the commonly used scripts.

### Building Plugin:
```bash
npm run build

# or for Angular
npm run build.angular
```

### Running Demos (interactive menu):
```bash
npm run demo.[ng|react|svelte|vue].[ios|android]

# Example:
npm run demo.svelte.ios
```

Or go into any demo's directory and run `ns run android` or `ns run ios`.

### CODE REVIEW

**Comment by farfromrefug** [comment]
@keerl very nice. I like it. A few things:
* when is the npm sync command called? 
* there are both `prepare` and `postinstall` scripts which seem to do the same thing. Both are run on `npm i`. We should only need one.
* about the setup script and copying of App_Resources. Shouldn t it be better to merge instead of heavy copy? Mostly only a few resources will change

**Comment by keerl** [comment]
- `npm sync` is called when you are updating the plugin dependencies. It is a manual operation. The idea being when a new version of something comes out lets say `@nativescript/core@8.1.1` or something we can update it in the template (https://github.com/nativescript-community/plugin-seed-tools/blob/e331c132f0498316940176473e443ed1258a5fd5/package.json) and then apply it to each plugin with `npm sync`. 
- I didn't notice both the `prepare` and `postinstall`, good catch. I'll remove the `prepare` and keep `postinstall`.
- Could you elaborate on what you mean by "merge instead of heavy copy" with the `App_Resources`? Right now, each plugin has their own `App_Resources` and if you want to add/overwrite anything in there you can put your custom files in `demo-snippets/App_Resources` and it will add (and possibly overwrite) those files to the specific demo's `App_Resources` directory.

**Comment by farfromrefug** [comment]
I mean it should not overwrite App_Ressources but instead merge the directories so that it only replaces files inside demo-snippets/App_Resources. Mostly only include.gradle and Podfile.will change

**Comment by keerl** [comment]
That's exactly what I intended and is how it behaves (at least on my end). If I add a custom `app.gradle` to `demo-snippets/App_Resources/Android` it will copy that over to the demo App_Resources. Everything else in there will stay the same.

**Pull request merged**
